In [1]:
import pandas as pd
import numpy as np

### Custom Lasso Regression Function 
##### Still figuring out how this works in sklearn (this is just the general implementation of Lasso Regression based on the basic understanding/functionality)

In [2]:
class CustomLasso:
    def __init__(self, alpha):
        self.w = None
        self.intercept_ = None
        self.coef_ = None
        self.lr = 0.01
        self.alpha = alpha

    def fit(self, x, y, epochs = 1000):
        dw = 0
        da = 0
        x = np.insert(x,0,1, axis =1)
        self.w = np.ones(x.shape[1])
        i = np.ones(x.shape[1])
        i[0] = 0
        for _ in range(epochs):
            y_pred = np.dot(x, self.w)
            dw = (1/x.shape[0])*(x.T.dot(y_pred - y))
            dw += self.alpha*np.sign(self.w)*i

            self.w = self.w- self.lr*dw

        self.intercept_ = self.w[0]
        self.coef_ = self.w[1:]

    def predict(self,x_test):
        return np.array(np.dot(x_test, self.coef_) + self.intercept_).flatten()


    

In [3]:
from sklearn.datasets import load_diabetes
df = load_diabetes(scaled=True,as_frame=True)
df = pd.DataFrame(pd.concat([df.data, df.target.rename('target')], axis = 1))


from sklearn.model_selection import train_test_split
x = df.drop(columns = 'target')
y = df['target']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.2, random_state=32)


#### Sklearn Lasso Regression

In [4]:
from sklearn.linear_model import Lasso
model = Lasso(2, tol = 0)
model.fit(x_train, y_train)
model.intercept_, model.coef_

(np.float64(153.50434527023046),
 array([ 0.        ,  0.        , 88.42369879,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , 15.86753678,  0.        ]))

In [5]:
model.predict(x_test)

array([154.0225863 , 156.86489572, 149.94132058, 148.39920281,
       151.76533675, 154.25097038, 160.04619793, 153.80362229,
       158.07378479, 159.00431624, 150.29508519, 160.63740476,
       160.76899902, 147.73121521, 148.30096067, 145.91832143,
       150.66678544, 156.35594512, 151.71847269, 152.25786752,
       149.58387053, 152.09757063, 150.19083747, 153.42045604,
       149.82876476, 153.94602544, 159.66731662, 164.61474542,
       155.50677783, 164.97353325, 156.33303734, 153.23179751,
       157.03508522, 150.95108844, 152.23488447, 152.33054727,
       154.02463551, 155.05199866, 149.70387836, 148.84914857,
       157.05600401, 149.59102737, 155.070971  , 152.65378322,
       151.54363043, 155.06604728, 157.07101996, 149.10751874,
       155.3702448 , 157.38643608, 150.91328578, 151.91156998,
       155.05828177, 155.34975666, 151.13444365, 153.4089691 ,
       151.14330609, 154.24893034, 154.53484273, 157.68297672,
       160.68876778, 154.2303952 , 160.85816208, 146.75

#### Custom Lasso Regression

In [6]:
model1 = CustomLasso(2)
model1.fit(x_train, y_train)
model1.intercept_, model1.coef_

(np.float64(153.51772249358083),
 array([ 1.21428121e-02,  4.93441156e-03,  3.21907323e+00,  2.06297208e-02,
         2.04648445e-03,  7.52681276e-03, -2.49909764e-02,  1.22796933e-02,
         2.17024511e+00,  3.25416799e-02]))

Here the intercept is almost same as sklearn lasso whereas the coef values are different but it performs the same task as irrelavant feature's weights minimizes/reduces towards 0 whereas the important features have more weights values.

In [7]:
model1.predict(x_test)

array([153.63395845, 153.61911496, 153.31826481, 153.33150848,
       153.43548827, 153.57402532, 153.8107119 , 153.52769625,
       153.76649574, 153.74345556, 153.35190999, 153.83532585,
       153.83472456, 153.22210824, 153.30138491, 153.0946494 ,
       153.38496428, 153.57650062, 153.43751244, 153.43750383,
       153.3356139 , 153.57213932, 153.26811114, 153.56536994,
       153.38167573, 153.59490421, 153.90779703, 153.8945467 ,
       153.67144113, 153.99593652, 153.63570615, 153.50854796,
       153.70637635, 153.56802736, 153.43479985, 153.38713004,
       153.56320596, 153.68344595, 153.32686316, 153.27728539,
       153.7656525 , 153.28865441, 153.6044858 , 153.50731011,
       153.42631246, 153.50696809, 153.56442564, 153.24579491,
       153.5581916 , 153.76289065, 153.43906709, 153.46300797,
       153.5404007 , 153.68612006, 153.47394556, 153.51651204,
       153.39715785, 153.56033673, 153.57186318, 153.72223937,
       153.84838788, 153.45238976, 153.69807203, 153.23