In [2]:
import pandas as pd
import numpy as np

### Custom Multi Linear Regression Function

In [3]:
class multiLinearRegression:
    def __init__(self):
        self.w = None
        self.coef_ = None
        self.intercept = None
    
    def fit(self,x, y):
        x = np.insert(x,0,1, axis=1)
        self.w = np.ones(x.shape[1])
        w = np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)
        self.coef_ = w[1:]
        self.intercept_ = w[0]

    def predict(self,x_test):
        return np.array(self.intercept_ + x_test.dot(self.coef_))
    

In [4]:
from sklearn.datasets import load_diabetes
df = load_diabetes(scaled=True,as_frame=True)
df = pd.DataFrame(pd.concat([df.data, df.target.rename('target')], axis = 1))
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0


In [5]:
from sklearn.model_selection import train_test_split
x = df.drop(columns = 'target')
y = df['target']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.2, random_state=32)

#### Sklearn Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.intercept_,lr.coef_

(np.float64(154.31230345901605),
 array([  32.50000078, -274.2083569 ,  501.52744069,  368.7931961 ,
        -822.31120988,  504.23867319,  101.57697155,  158.16545687,
         744.91541712,   78.40553632]))

In [8]:
lr.predict(x_test)

array([172.60221563, 176.28452979, 104.69642913, 123.73172065,
       125.12918841, 175.52860928, 221.40057635, 160.84007097,
       216.01436124, 188.23526082,  95.28269009, 238.57773462,
       223.41312722,  69.82251258, 105.75775874,  55.78523953,
       116.04227362, 146.99512516, 178.52120042, 147.16269541,
       110.60045446, 156.88298979,  82.30039499, 185.56700021,
       145.63102069, 165.09136947, 291.18274014, 242.86916518,
       211.93210439, 287.45873377, 196.59135902, 127.43771823,
       209.84018734, 183.1606271 , 150.20425299, 114.49182187,
       195.96246781, 213.03006633,  99.00218774,  91.55574708,
       225.40664872, 103.49093388, 133.76320566, 160.23604055,
       137.48284804, 141.62538982, 157.64325814,  90.51604444,
       173.31917991, 232.56143464, 165.0880776 , 147.67363064,
       169.44439603, 211.64268676, 152.86666838, 108.86805754,
       122.6790726 , 171.54184272, 170.17264755, 207.48159075,
       219.34541916, 164.91624615, 179.59840729, 109.11

#### Custom Linear Regression

In [9]:
lr1 = multiLinearRegression()
lr1.fit(x_train,y_train)
lr1.intercept_, lr1.coef_


(np.float64(154.31230345901602),
 array([  32.50000078, -274.2083569 ,  501.52744069,  368.7931961 ,
        -822.31120988,  504.23867319,  101.57697155,  158.16545687,
         744.91541712,   78.40553632]))

In [10]:
lr1.predict(x_test)

array([172.60221563, 176.28452979, 104.69642913, 123.73172065,
       125.12918841, 175.52860928, 221.40057635, 160.84007097,
       216.01436124, 188.23526082,  95.28269009, 238.57773462,
       223.41312722,  69.82251258, 105.75775874,  55.78523953,
       116.04227362, 146.99512516, 178.52120042, 147.16269541,
       110.60045446, 156.88298979,  82.30039499, 185.56700021,
       145.63102069, 165.09136947, 291.18274014, 242.86916518,
       211.93210439, 287.45873377, 196.59135902, 127.43771823,
       209.84018734, 183.1606271 , 150.20425299, 114.49182187,
       195.96246781, 213.03006633,  99.00218774,  91.55574708,
       225.40664872, 103.49093388, 133.76320566, 160.23604055,
       137.48284804, 141.62538982, 157.64325814,  90.51604444,
       173.31917991, 232.56143464, 165.0880776 , 147.67363064,
       169.44439603, 211.64268676, 152.86666838, 108.86805754,
       122.6790726 , 171.54184272, 170.17264755, 207.48159075,
       219.34541916, 164.91624615, 179.59840729, 109.11