In [2]:
import pandas as pd
import numpy as np

### Custom Ridge Regression Function

In [112]:
class CustomRidge:
    def __init__(self,alpha = 0):
        self.w = None
        self.coef_ = None
        self.intercept_ = None
        self.alpha = alpha

    def fit(self,x,y):
        x = np.insert(x,0,1,axis = 1)
        self.w = np.ones(x.shape[1])
        i = np.identity(x.shape[1])
        i[0][0] = 0
        
        self.w = x.T.dot(y).dot(np.linalg.inv(x.T.dot(x)+ (self.alpha*i)))
        self.intercept_ = self.w[0]
        self.coef_ = self.w[1:]

    def predict(self,x_test):
        return np.array(x_test.dot(self.coef_) + self.intercept_).flatten()

In [127]:
from sklearn.datasets import load_diabetes
df = load_diabetes(scaled=True,as_frame=True)
df = pd.DataFrame(pd.concat([df.data, df.target.rename('target')], axis = 1))


from sklearn.model_selection import train_test_split
x = df.drop(columns = 'target')
y = df['target']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.2, random_state=32)

#### Sklearn Ridge Regression

In [114]:
from sklearn.linear_model import Ridge
model = Ridge(2)
model.fit(x_train, y_train)
model.intercept_, model.coef_


(np.float64(153.65284698676408),
 array([  40.8359425 ,  -41.34812254,  199.5014845 ,  148.97046239,
          21.77633064,    1.62985588, -110.60193277,   92.73191283,
         176.72025663,  100.45346248]))

In [115]:
model.predict(x_test)

array([162.26564789, 154.57892593, 114.4544938 , 132.11420077,
       129.80564946, 177.27992306, 186.88535355, 155.75159426,
       171.71959318, 173.99498106, 130.7622733 , 194.05542773,
       192.10760507, 122.03038608, 134.59343744, 103.03119156,
       136.88553257, 140.03966147, 166.48220909, 168.46458029,
       111.38341576, 161.71344309, 114.53399567, 173.35504263,
       131.68713541, 157.99537274, 227.99851082, 175.16792515,
       190.66999887, 199.03151368, 167.15560275, 154.47102113,
       186.24312182, 165.40957598, 139.85185997, 118.85899969,
       179.72413705, 189.90468321, 126.76491737, 119.02061696,
       189.95309432, 112.75006125, 148.29378656, 161.25758657,
       137.40192665, 144.17019506, 159.79710066, 123.73233956,
       150.07078241, 188.01154501, 155.20469509, 158.88034367,
       168.01672408, 185.03365328, 168.09904019, 130.39829118,
       122.54131673, 159.12970043, 166.25866941, 165.78156372,
       178.06697954, 154.69206644, 163.75184084, 114.71

#### Custom Ridge Regression

In [116]:
model1 = CustomRidge(2)
model1.fit(x_train, y_train)
model1.intercept_, model1.coef_

(np.float64(153.65284698676408),
 array([  40.8359425 ,  -41.34812254,  199.5014845 ,  148.97046239,
          21.77633064,    1.62985588, -110.60193277,   92.73191283,
         176.72025663,  100.45346248]))

In [117]:
model1.predict(x_test)

array([162.26564789, 154.57892593, 114.4544938 , 132.11420077,
       129.80564946, 177.27992306, 186.88535355, 155.75159426,
       171.71959318, 173.99498106, 130.7622733 , 194.05542773,
       192.10760507, 122.03038608, 134.59343744, 103.03119156,
       136.88553257, 140.03966147, 166.48220909, 168.46458029,
       111.38341576, 161.71344309, 114.53399567, 173.35504263,
       131.68713541, 157.99537274, 227.99851082, 175.16792515,
       190.66999887, 199.03151368, 167.15560275, 154.47102113,
       186.24312182, 165.40957598, 139.85185997, 118.85899969,
       179.72413705, 189.90468321, 126.76491737, 119.02061696,
       189.95309432, 112.75006125, 148.29378656, 161.25758657,
       137.40192665, 144.17019506, 159.79710066, 123.73233956,
       150.07078241, 188.01154501, 155.20469509, 158.88034367,
       168.01672408, 185.03365328, 168.09904019, 130.39829118,
       122.54131673, 159.12970043, 166.25866941, 165.78156372,
       178.06697954, 154.69206644, 163.75184084, 114.71