In [3]:
import pandas as pd
import numpy as np

### Custom Linear Regression Function (for 1 dependant and 1 independant feature)

In [20]:
class LinearRegressionCustom:
    def __init__(self):
        self.coef_ = None
        self.intercept_= None

    def fit(self,x,y):
        num = 0
        den = 0
        x = x.values.flatten()
        y = y.values.flatten()

        for i in range(x.shape[0]):
            num = num + (x[i]-x.mean())*(y[i]-y.mean())
            den = den + (x[i]-x.mean())**2
        self.coef_ = num/den
        self.intercept_= y.mean()-self.coef_*x.mean()

    def predict(self, x_test):
        return np.array(self.coef_*x_test + self.intercept_).flatten()


In [4]:
from sklearn.datasets import load_diabetes

In [5]:
df = load_diabetes(as_frame=True, scaled=False)

In [6]:

df = pd.DataFrame(pd.concat([df.data,df.target.rename('Target')], axis=1))

In [7]:
x = df[['bmi']]
y = df.Target

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=32)

#### Sklearn Linear Regression

In [9]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)

In [10]:
lr.coef_, lr.intercept_

(array([10.24865499]), np.float64(-117.1071883461681))

In [23]:
lr.predict(x_test)

array([148.33297589, 191.37732684, 121.68647291,  98.11456644,
       136.0345899 , 158.58163088, 218.02382982, 156.53189988,
       193.42705784, 209.82490582, 123.73620391, 224.17302281,
       226.22275381, 100.16429743, 100.16429743,  86.84104595,
       125.78593491, 188.30273035, 136.0345899 , 144.23351389,
       114.51241442, 126.81080041, 130.9102624 , 147.30811039,
       113.48754892, 151.40757238, 202.65084733, 275.41629776,
       166.78055487, 270.29197026, 182.15353735, 150.38270688,
       185.22813385, 110.41295242, 143.20864839, 149.35784139,
       156.53189988, 158.58163088, 117.58701092, 110.41295242,
       179.07894086, 119.63674192, 166.78055487, 142.18378289,
       133.9848589 , 177.02920986, 200.60111633, 117.58701092,
       176.00434436, 184.20326835, 123.73620391, 136.0345899 ,
       173.95461336, 162.68109287, 123.73620391, 151.40757238,
       130.9102624 , 159.60649637, 162.68109287, 192.40219234,
       223.14815731, 170.88001686, 241.59573629,  83.76

#### Custom Linear Regression 

In [21]:
lr1 = LinearRegressionCustom()
lr1.fit(x_train, y_train)

In [22]:
lr1.coef_, lr1.intercept_

(np.float64(10.248654989668756), np.float64(-117.10718834616799))

In [24]:
lr1.predict(x_test)

array([148.33297589, 191.37732684, 121.68647291,  98.11456644,
       136.0345899 , 158.58163088, 218.02382982, 156.53189988,
       193.42705784, 209.82490582, 123.73620391, 224.17302281,
       226.22275381, 100.16429743, 100.16429743,  86.84104595,
       125.78593491, 188.30273035, 136.0345899 , 144.23351389,
       114.51241442, 126.81080041, 130.9102624 , 147.30811039,
       113.48754892, 151.40757238, 202.65084733, 275.41629776,
       166.78055487, 270.29197026, 182.15353735, 150.38270688,
       185.22813385, 110.41295242, 143.20864839, 149.35784139,
       156.53189988, 158.58163088, 117.58701092, 110.41295242,
       179.07894086, 119.63674192, 166.78055487, 142.18378289,
       133.9848589 , 177.02920986, 200.60111633, 117.58701092,
       176.00434436, 184.20326835, 123.73620391, 136.0345899 ,
       173.95461336, 162.68109287, 123.73620391, 151.40757238,
       130.9102624 , 159.60649637, 162.68109287, 192.40219234,
       223.14815731, 170.88001686, 241.59573629,  83.76